steps:
  - id: "Executando docker-compose"
    name: 'gcr.io/$PROJECT_ID/docker-compose:1.25.5'
    args: ['-f','docker-compose.prod.yaml', 'up','-d']

  - id: "Executando docker ps"
    name: 'gcr.io/cloud-builder/docker'
    args: ['ps']

  - id: "Executando composer"
    name: 'gcr.io/cloud-builder/docker'
    args: ['exec','-t','app','composer','install']

  - id: "Copiando .env"
    name: 'gcr.io/cloud-builder/docker'
    args: ['exec','-t','app','cp','env.example','.env']

  - id: "Rodando key:generate"
    name: 'gcr.io/cloud-builder/docker'
    args: ['exec','-t','app','php','/var/www/artisan','key:generate']

  - id: "Rodando as migrações"
    name: 'gcr.io/cloud-builder/docker'
    args: ['exec','-t','app','php','/var/www/artisan','migration']

  - id: "Rodando php-unit"
    name: 'gcr.io/cloud-builder/docker'
    args: ['exec','-t','app','php','/var/www/artisan/vendor/bin/phpunit','-c', '/var/www/phpunit.xml']





