version: '3'
services:
  #PHP LARAVEL
  app:
    build:
      context: .
      dockerfile: .docker/laravel/Dockerfile
    container_name: app
    # entrypoint: dockerize -template .docker/laravel/.env:.env -wait tcp://db:3306 -timeout 3m .docker/laravel/entrypoint.sh
    # environment:
    #   - DB_HOST=db
    #   - DB_DATABASE=laravel
    #   - DB_USERNAME=root
    #   - DB_PASSWORD=root
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - db
      - redis

  #NGINX
  nginx:
    build:
      context: .docker/nginx/
      dockerfile: Dockerfile
    container_name: nginx
    entrypoint: dockerize -template /nginx.conf:/etc/nginx/conf.d/nginx.conf nginx -g "daemon off;"
    environment:
      - NGINX_PORT=80
      - APP_HOST=app
      - APP_PORT=9000
    restart: always
    tty: true
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - app

  #REDIS
  redis:
    image: redis:6.0.3-alpine
    container_name: redis
    restart: always
    tty: true
    networks:
      - app-network
    expose:
      - 6379

  #MYSQL
  db:
    image: mysql:5.7
    command: --innodb_use_native_aio=0
    container_name: db
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - .docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - app-network

#networks
networks:
  app-network:
    driver: bridge
